name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
